### ISSUE TITLE
case / esac not being properly parsed

### ISSUE THREAD

**Issue by sergeyklay** [maelvalais/vscode_autotools#4]
Hello,

The square brackets in the `case...esac` statement breaks the syntax highlighting for ac files in VS Code:

![image](https://user-images.githubusercontent.com/1256298/50493805-7508ee80-0a28-11e9-8c5a-4f822e6e4386.png)

P.S. The same issue in the Sublime Text 2 / 3

**Comment by sergeyklay** [comment]
Never mind. I shouldn't use square brackets in the `case...esac` statement.

**Comment by maelvalais** [comment]
Hi!

Thanks for the report anyway 🙂 Nice to see that people use and care about this small project! 😊

**Comment by sergeyklay** [comment]
Thank you for the extension!
